apiVersion: v1
kind: ReplicationController
metadata:
    name: kube-dns-v6
    #namespace: kube-system
    labels:
        k8s-app: kube-dns
        version: v6
        kubernetes.io/cluster-service: "true"
spec:
    replicas: 1
    selector:
        k8s-app: kube-dns
        version: v6
    template:
        metadata:
          labels:
            k8s-app: kube-dns
            version: v6
            kubernetes.io/cluster-service: "true"
        spec:
          containers:  
          - name: kube2sky
            image: 10.25.31.16:5000/kube2sky:1.15
            resources:
              limits:
                cpu: 100m
                memory: 50Mi
            args:
            # command = "/kube2sky"
            - --kube-master-url=http://10.25.31.16:8080 #change to your master url
            - --etcd-server=http://10.25.31.16:2379
            - --domain=yin.com
          - name: skydns
            image: 10.25.31.16:5000/skydns:2015-03-11-001
            resources:
              limits:
                cpu: 100m
                memory: 50Mi
            args:
            # command = "/skydns"
            - -machines=http://10.25.23.165:2379
            - -addr=0.0.0.0:53
            - -domain=yin.com
            - -nameservers=10.25.20.251:53,10.25.3.210:53,172.17.40.1:53
            ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          dnsPolicy: Default  # Don't use cluster DNS.
