apiVersion: v1
kind: ReplicationController
metadata:
  name: simpleweb-rc
  labels:
    k8s-app: simpleweb
    kubernetes.io/cluster-service: "true"
spec:
    replicas: 1
    selector:
        k8s-app: simpleweb
    template:
        metadata:
          labels:
            k8s-app: simpleweb
            kubernetes.io/cluster-service: "true"
        spec:
            containers:
            - image: 10.25.31.31:5000/simpleweb:1.0
              name: war
              lifecycle:
                postStart:
                  exec:
                    command:
                      - "cp"
                      - "/simpleweb.war"
                      - "/app"
              volumeMounts:
              - mountPath: /app
                name: app-volume
            - image: 10.25.31.31:5000/tomcat
              name: tomcat
              volumeMounts:
              - mountPath: /usr/local/tomcat/webapps
                name: app-volume
              ports:
              - name: http
                containerPort: 8080
              - name: dubbo
                containerPort: 20910
              - name: dubug
                containerPort: 8000
                hostPort: 30001
              - name: tcp
                containerPort: 40001
                hostPort: 30002
              - name: udp
                containerPort: 40002
                hostPort: 30003
            volumes:
            - name: app-volume
              emptyDir: {}
