apiVersion: v1
kind: Service
metadata:
  name: simpleweb-svc
  labels:
    k8s-app: simpleweb
    kubernetes.io/cluster-service: "true"
spec:
  #type: NodePort
  clusterIP: None
  selector:
    k8s-app: simpleweb
  ports:
  - port: 80
    targetPort: 8080
    #nodePort: 30005
