apiVersion: v1
kind: Pod
metadata:
    name: busybox
    namespace: default
spec:
    containers:
    - name: busybox 
      image: gcr.io/google-containers/busybox
      command:
      - sleep
      - "3600"
      imagePullPolicy: IfNotPresent
    restartPolicy: Always