apiVersion: v1
kind: ReplicationController
metadata:
    name: kube-dns-v6
    namespace: kube-system
    labels:
        k8s-app: kube-dns
        version: v6
        kubernetes.io/cluster-service: "true"
spec:
    replicas: 1
    selector:
        k8s-app: kube-dns
        version: v6
    template:
        metadata:
          labels:
            k8s-app: kube-dns
            version: v6
            kubernetes.io/cluster-service: "true"
        spec:
          containers:  
          - name: kube2sky
            image: gcr.io/google_containers/kube2sky:1.11
            resources:
              limits:
                cpu: 100m
                memory: 50Mi
            args:
            # command = "/kube2sky"
            - --kube_master_url=http://10.25.23.165:8080 #change to your master url
            - --etcd-server=http://10.25.23.165:2379
            - --domain=zxq.com
          - name: skydns
            image: gcr.io/google_containers/skydns:2015-03-11-001
            resources:
              limits:
                cpu: 100m
                memory: 50Mi
            args:
            # command = "/skydns"
            - -machines=http://10.25.23.165:2379
            - -addr=0.0.0.0:53
            - -domain=zxq.com.
            ports:
            - containerPort: 53
              name: dns
              protocol: UDP
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
          dnsPolicy: Default  # Don't use cluster DNS.