apiVersion: v1
kind: Service
metadata:
  name: javaweb-svc
  labels:
    k8s-app: javaweb
    kubernetes.io/cluster-service: "true"
spec:
  clusterIP: None
  selector:
    k8s-app: javaweb
  ports:
  - port: 80   
    targetPort: 8080