apiVersion: v1
kind: ReplicationController
metadata:
  name: nginxplus-rc
  labels:
    k8s-app: nginxplus    
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: nginxplus
  template:
    metadata:
      labels:
        k8s-app: nginxplus
    spec:
      nodeSelector: 
        kubernetes.io/hostname: k8s-node01
      containers:
      - image: donbstringham/nginxplus
        name: nginxplus 
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: http-alt
          containerPort: 8080
          hostPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: etc-nginx-confd
      volumes:
      - hostPath:
          path: /etc/nginx/conf.d
        name: etc-nginx-confd