apiVersion: v1
kind: Service
metadata:
  name: simplewar-svc
  labels:
    k8s-app: simplewar
    kubernetes.io/cluster-service: "true"
spec:
  clusterIP: None
  selector:
    k8s-app: simplewar
  ports:
  - port: 80   
    targetPort: 8080